# SPDX-License-Identifier: GPL-2.0-only
mtk-ccci-objs := mtk_ccci_core.o mtk_ccci_modem.o mtk_ccci_port.o \
		 mtk_ccci_tty.o mtk_ccmni.o mtk_ccci_cldma.o \
		 mtk_ccci_plat.o

obj-$(CONFIG_MTK_CCCI) += mtk-ccci.o
